//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmanAssignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrudOperation
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string FatherName { get; set; }
        public string MobileNumber { get; set; }
        public string Landline { get; set; }
        public string PostalAddress { get; set; }
        public string Domicile { get; set; }
        public string country { get; set; }
        public string City { get; set; }
        public string Nationality { get; set; }
        public string CNIC { get; set; }
        public string ExService { get; set; }
        public int ID { get; set; }
    }
}
